# Generated by Django 3.0.6 on 2020-06-07 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('primaryCategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='stock_pics')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('sellers_message', models.TextField(max_length=256)),
                ('more_details', models.TextField(max_length=1000)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('minimum_order', models.PositiveIntegerField(blank=True)),
                ('rate', models.PositiveIntegerField(blank=True)),
                ('breed', models.CharField(max_length=200)),
                ('delivery_within', models.PositiveIntegerField()),
                ('deliverytimechoice', models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'weeks')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Category')),
                ('location', models.ManyToManyField(to='stock.Location')),
                ('per_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_unit', to='stock.Unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_unit', to='stock.Unit')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-posted_date',),
            },
        ),
    ]
