# Generated by Django 3.0.6 on 2020-06-08 09:18

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.JPG', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profile_pics'),
        ),
    ]
